---
name: Multi Arch Signed

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: read
  packages: write
  pull-requests: read
  id-token: write

env:
  IMAGE_NAME: test-multi-arch-signed
  IMAGE_TAG: 0.1.0

jobs:
  arrange:
    name: Arrange
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "GitHub token secret is not set"
            exit 1
          fi
      - name: Delete existing packages if any
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/${{ github.repository_owner }}/packages/container/test-docker-build-images%2F${{ env.IMAGE_NAME }} || echo "No existing mono-arch package to delete"

  act-build-image:
    name: Act - Build image
    needs: arrange
    uses: hoverkraft-tech/ci-github-container/.github/workflows/docker-build-images.yml@main
    secrets:
      oci-registry-password: ${{ secrets.GITHUB_TOKEN }}
    with:
      sign: true
      images: |
        [
          {
            "name": "test-multi-arch-signed",
            "context": ".",
            "dockerfile": "./tests/application/Dockerfile",
            "build-args": { "BUILD_RUN_ID": "${{ github.run_id }}" },
            "target": "prod",
            "platforms": ["linux/amd64", "linux/arm64"],
            "tag": "0.1.0"
          }
        ]

  assert-image-versions:
    name: Assert - Image versions
    needs: act-build-image
    runs-on: ubuntu-latest
    steps:
      - name: Verify image exists
        run: docker pull ghcr.io/hoverkraft-tech/test-docker-build-images/${IMAGE_NAME}:${IMAGE_TAG}

      - name: Verify packages tagged and untagged versions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          versions_count=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/${{ github.repository_owner }}/packages/container/test-docker-build-images%2F${IMAGE_NAME}/versions | jq '. | length')

          if [ "$versions_count" -ne 2 ]; then
            echo "Expected 2 versions (1 tagged and 1 untagged), but found $versions_count"
            exit 1
          fi

  assert-signed-images:
    name: Assert - Signed images
    needs: act-build-image
    runs-on: ubuntu-latest
    steps:
      - uses: sigstore/cosign-installer@v4.0.0

      - name: Verify mono-arch image signature (Signed with GitHub OIDC Token)
        run: cosign verify --key github://hoverkraft-tech/ci-bot --output json ghcr.io/hoverkraft-tech/${IMAGE_NAME}:${IMAGE_TAG} | jq .
