---
name: Single Arch Unsigned

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: read
  packages: write
  pull-requests: read
  id-token: write

env:
  IMAGE_NAME: test-single-arch-unsigned
  IMAGE_TAG: 0.1.0

jobs:
  arrange:
    name: Arrange
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "GitHub token secret is not set"
            exit 1
          fi
      - name: Delete existing packages if any
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/${{ github.repository_owner }}/packages/container/test-docker-build-images%2F${{ env.IMAGE_NAME }} || echo "No existing mono-arch package to delete"

  act-build-image:
    name: Act - Build image
    needs: arrange
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ghcr.io/hoverkraft-tech/test-docker-build-images/${{ env.IMAGE_NAME }}
          tags: type=semver,pattern={{raw}},value=0.1.0
          flavor: latest=false

      - name: Build and Push container images
        uses: docker/build-push-action@v6.18.0
        id: build-and-push
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./tests/application/Dockerfile
          target: prod
          provenance: false
          build-args: |
            BUILD_RUN_ID=${{ github.run_id }}

  assert-image-versions:
    name: Assert - Image versions
    needs: act-build-image
    runs-on: ubuntu-latest
    steps:
      - name: Verify image exists
        run: docker pull ghcr.io/hoverkraft-tech/test-docker-build-images/${IMAGE_NAME}:${IMAGE_TAG}

      - name: Verify packages tagged and untagged versions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          versions_count=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/${{ github.repository_owner }}/packages/container/test-docker-build-images%2F${IMAGE_NAME}/versions | jq '. | length')

          if [ "$versions_count" -ne 1 ]; then
            echo "Expected 1 version (1 tagged), but found $versions_count"
            exit 1
          fi
